# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
branches:
  only:
    - master
before_install:
- gem install xcpretty -N
- gem install cocoapods
script:
- set -o pipefail && xcodebuild test -workspace Example/Pollock.xcworkspace -scheme Pollock-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
