source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Pollock', :exclusive => true do
  pod "Pollock", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Pollock", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
